INSERT INTO `xmlagent`.`agent` (`name`, `surname`, `approved`, `email`, `password`) VALUES ('Dragan','Dulic',1,'dragan.dulic1@gmail.com','vvvv');
INSERT INTO `xmlagent`.`agent` (`name`, `surname`, `approved`, `email`, `password`) VALUES ('Mika','Mikic',1,'donthavename3478@gmail.com','aaaa');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('1','01/07/2018','07/07/2018','Kod sajma',1,'Master','2.1','1','1');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Jevrejska 1','Novi Sad','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('2','16/06/2018','20/06/2018','Centar',1,'Centar','4','1','2');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Bul. Kralja Petra 4','Beograd','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('1','20/06/2018','27/06/2018','Dobar sa bazenom',0,'Novi Sad','3','1','3');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Bul. Evrope 34','Novi Sad','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('4','23/06/2018','27/06/2018','Odlicna usluga',1,'Putnik','5','1','4');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Fruskogorska 54','Novi Sad','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('3','01/07/2018','07/07/2018','Kod sajma',1,'Putnikk','2.1','1','5');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Jevrejska 1','Subotica','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('5','01/07/2018','07/07/2018','Kod sajma',1,'Masterr','3.1','1','6');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Jevrejska 1','Subotica','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('2','01/07/2018','07/07/2018','Kod sajma',1,'Moskvaa','4.1','1','7');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Jevrejska 1','Subotica','Srbija');
INSERT INTO `xmlagent`.`accommodation` (`category`,`reserved_from`,`reserved_to`,`description`,`free`,`name`,`rating`,`agent_id`,`location_id`) VALUES ('3','01/07/2018','07/07/2018','Kod sajma',1,'AquaLux','5.0','1','8');
INSERT INTO `xmlagent`.`location` (`address`,`city`,`country`) VALUES ('Jevrejska 1','Subotica','Srbija');
