//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 07:47:31 PM CEST 
//


package com.travel.Agent.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="WiFi" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="TV" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Parking" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Kitchen" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Breakfast" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="HalfBoard" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="FullBoard" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Bathroom" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "wiFi",
    "tv",
    "parking",
    "kitchen",
    "breakfast",
    "halfBoard",
    "fullBoard",
    "bathroom"
})
@XmlRootElement(name = "AdditionalServices")
@Entity
public class AdditionalServices {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    @XmlElement(name = "Id")
    protected long id;
	
	@Column
    @XmlElement(name = "WiFi", defaultValue = "false")
    protected boolean wiFi;
	
	@Column
    @XmlElement(name = "TV", defaultValue = "false")
    protected boolean tv;
	
	@Column
    @XmlElement(name = "Parking", defaultValue = "false")
    protected boolean parking;
	
	@Column
    @XmlElement(name = "Kitchen", defaultValue = "false")
    protected boolean kitchen;
	
	@Column
    @XmlElement(name = "Breakfast", defaultValue = "false")
    protected boolean breakfast;
	
	@Column
    @XmlElement(name = "HalfBoard", defaultValue = "false")
    protected boolean halfBoard;
	
	@Column
    @XmlElement(name = "FullBoard", defaultValue = "false")
    protected boolean fullBoard;
	
	@Column
    @XmlElement(name = "Bathroom", defaultValue = "false")
    protected boolean bathroom;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the wiFi property.
     * 
     */
    public boolean isWiFi() {
        return wiFi;
    }

    /**
     * Sets the value of the wiFi property.
     * 
     */
    public void setWiFi(boolean value) {
        this.wiFi = value;
    }

    /**
     * Gets the value of the tv property.
     * 
     */
    public boolean isTV() {
        return tv;
    }

    /**
     * Sets the value of the tv property.
     * 
     */
    public void setTV(boolean value) {
        this.tv = value;
    }

    /**
     * Gets the value of the parking property.
     * 
     */
    public boolean isParking() {
        return parking;
    }

    /**
     * Sets the value of the parking property.
     * 
     */
    public void setParking(boolean value) {
        this.parking = value;
    }

    /**
     * Gets the value of the kitchen property.
     * 
     */
    public boolean isKitchen() {
        return kitchen;
    }

    /**
     * Sets the value of the kitchen property.
     * 
     */
    public void setKitchen(boolean value) {
        this.kitchen = value;
    }

    /**
     * Gets the value of the breakfast property.
     * 
     */
    public boolean isBreakfast() {
        return breakfast;
    }

    /**
     * Sets the value of the breakfast property.
     * 
     */
    public void setBreakfast(boolean value) {
        this.breakfast = value;
    }

    /**
     * Gets the value of the halfBoard property.
     * 
     */
    public boolean isHalfBoard() {
        return halfBoard;
    }

    /**
     * Sets the value of the halfBoard property.
     * 
     */
    public void setHalfBoard(boolean value) {
        this.halfBoard = value;
    }

    /**
     * Gets the value of the fullBoard property.
     * 
     */
    public boolean isFullBoard() {
        return fullBoard;
    }

    /**
     * Sets the value of the fullBoard property.
     * 
     */
    public void setFullBoard(boolean value) {
        this.fullBoard = value;
    }

    /**
     * Gets the value of the bathroom property.
     * 
     */
    public boolean isBathroom() {
        return bathroom;
    }

    /**
     * Sets the value of the bathroom property.
     * 
     */
    public void setBathroom(boolean value) {
        this.bathroom = value;
    }

}
