//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 07:30:19 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.travel.com/accommodation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.travel.Agent.model;
