//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.06 at 07:47:31 PM CEST 
//


package com.travel.Agent.model;



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;






/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="RoomType" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="Price" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="12" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    "roomType",
    "price",
    "january",
    "february",
    "march",
    "april",
    "may",
    "june",
    "july",
    "august",
    "september",
    "october",
    "november",
    "december"
})
@XmlRootElement(name = "PricePlan")
@Entity
public class PricePlan {

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    @XmlElement(name = "Id")
    protected long id;
	
	@Column
    @XmlElement(name = "RoomType", defaultValue = "2")
    protected int roomtype;
	
	
	
	@ManyToOne
	@XmlElement(name = "Accommodation", required = true)
    protected Accommodation accommodation;

	protected int january;
	
	protected int february;
	
	protected int march;
	
	protected int april;
	
	protected int may;
	
	protected int june;
	
	protected int july;
	
	protected int august;
	
	protected int september;
	
	protected int october;
	
	protected int november;
	
	protected int december;
	
	
	   /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the roomType property.
     * 
     */
    public int getRoomType() {
        return roomtype;
    }

    /**
     * Sets the value of the roomType property.
     * 
     */
    public void setRoomType(int value) {
        this.roomtype = value;
    }

   
    /**
     * Gets the value of the accommodation property.
     * 
     * @return
     *     possible object is
     *     {@link Accommodation }
     *     
     */
    public Accommodation getAccommodation() {
        return accommodation;
    }

    /**
     * Sets the value of the accommodation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Accommodation }
     *     
     */
    public void setAccommodation(Accommodation value) {
        this.accommodation = value;
    }

    /**
     * Gets the value of the january property.
     * 
     */
    public int getJanuary() {
        return january;
    }

    /**
     * Sets the value of the january property.
     * 
     */
    public void setJanuary(int value) {
        this.january = value;
    }

    /**
     * Gets the value of the february property.
     * 
     */
    public int getFebruary() {
        return february;
    }

    /**
     * Sets the value of the february property.
     * 
     */
    public void setFebruary(int value) {
        this.february = value;
    }

    /**
     * Gets the value of the march property.
     * 
     */
    public int getMarch() {
        return march;
    }

    /**
     * Sets the value of the march property.
     * 
     */
    public void setMarch(int value) {
        this.march = value;
    }

    /**
     * Gets the value of the april property.
     * 
     */
    public int getApril() {
        return april;
    }

    /**
     * Sets the value of the april property.
     * 
     */
    public void setApril(int value) {
        this.april = value;
    }

    /**
     * Gets the value of the may property.
     * 
     */
    public int getMay() {
        return may;
    }

    /**
     * Sets the value of the may property.
     * 
     */
    public void setMay(int value) {
        this.may = value;
    }

    /**
     * Gets the value of the june property.
     * 
     */
    public int getJune() {
        return june;
    }

    /**
     * Sets the value of the june property.
     * 
     */
    public void setJune(int value) {
        this.june = value;
    }

    /**
     * Gets the value of the july property.
     * 
     */
    public int getJuly() {
        return july;
    }

    /**
     * Sets the value of the july property.
     * 
     */
    public void setJuly(int value) {
        this.july = value;
    }

    /**
     * Gets the value of the august property.
     * 
     */
    public int getAugust() {
        return august;
    }

    /**
     * Sets the value of the august property.
     * 
     */
    public void setAugust(int value) {
        this.august = value;
    }

    /**
     * Gets the value of the september property.
     * 
     */
    public int getSeptember() {
        return september;
    }

    /**
     * Sets the value of the september property.
     * 
     */
    public void setSeptember(int value) {
        this.september = value;
    }

    /**
     * Gets the value of the october property.
     * 
     */
    public int getOctober() {
        return october;
    }

    /**
     * Sets the value of the october property.
     * 
     */
    public void setOctober(int value) {
        this.october = value;
    }

    /**
     * Gets the value of the november property.
     * 
     */
    public int getNovember() {
        return november;
    }

    /**
     * Sets the value of the november property.
     * 
     */
    public void setNovember(int value) {
        this.november = value;
    }

    /**
     * Gets the value of the december property.
     * 
     */
    public int getDecember() {
        return december;
    }

    /**
     * Sets the value of the december property.
     * 
     */
    public void setDecember(int value) {
        this.december = value;
    }


}
